apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 1
  template:
    spec:
      ports:
        - name: default
          containerPort: 7654
      template:
        metadata:
            labels:
                app.kubernetes.io/instance: "simple-game-server:bns"
                app.kubernetes.io/part-of: "env-wdfbzx"  
        spec:
          nodeSelector:
            agentpool: agonespool  # Ensure this matches the label of your node pool
          tolerations:
            - 
              key: "agones"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          containers:
            - name: simple-game-server
              image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.33
              resources:
                requests:
                  memory: 64Mi
                  cpu: 20m
                limits:
                  memory: 64Mi
                  cpu: 20m